### ISSUE TITLE
Error building on Banana Pi

### ISSUE THREAD

**Issue by willief** [happybeing/safenetwork-farming#1]
I get this error while executing build.sh on a Banana Pi M1 

Linux bpi-iot-ros-ai 3.4.112-BPI-M1-Kernel #1 SMP PREEMPT Wed Jul 25 18:55:12 CST 2018 armv7l armv7l armv7l GNU/Linux

+ cargo update
    Updating crates.io index
    Updating git repository `https://github.com/mibac138/indicatif`
    Updating git repository `https://github.com/maidsafe/safe-network-launch-tool.git`
    Updating git repository `https://github.com/maidsafe/safe_client_libs`
    Updating git repository `https://github.com/maidsafe/safe_bindgen`
    Updating git repository `https://github.com/maidsafe/safe-nd.git`
error: failed to select a version for `bincode`.
    ... required by package `safe_app v0.16.3 (https://github.com/maidsafe/safe_client_libs#449a5e5e)`
    ... which is depended on by `safe-api v0.14.0 (/homes/farmer/safe-api/safe-api)`
    ... which is depended on by `safe-authd v0.0.10 (/homes/farmer/safe-api/safe-authd)`
versions that meet the requirements `^1.2.1` are: 1.3.1, 1.2.1

all possible versions conflict with previously selected packages.

  previously selected package `bincode v1.1.4`
    ... which is depended on by `safe-nd v0.10.0`
    ... which is depended on by `safe-api v0.14.0 (/homes/farmer/safe-api/safe-api)`
    ... which is depended on by `safe-authd v0.0.10 (/homes/farmer/safe-api/safe-authd)`

failed to select a version for `bincode` which could resolve this conflict

real	0m4.387s
user	0m1.620s
sys	0m0.300s
+ cargo build --release

**Comment by happybeing** [comment]
This looks like a 'normal' build error. The current master branch was not building recently due to ongoing Maidsafe changes so I'd check this first - or better check out the last good release for now and test with that. I'll close this for now, but if you believe this to be a problem with the scripts please reopen with details. Thanks for reporting!
